defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
#    [entryPoints.http.redirect]
#    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/certificate/ca.pem"
      keyFile = "/certificate/ca-key.pem"
#[traefikLog]
#  filePath = "/log/traefik_all.log"
#  format = "json"
#[accessLog]
#  filePath = "/log/traefik.log"
#  format = "json"

	
[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "localhost"
watch = true
exposedByDefault = false

[acme]
email = "alejo.gomez.h@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
